from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


def _load_json(path: Path) -> dict:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected JSON object in {path.as_posix()}")
    return payload


def _normalize_pattern_key(pattern: str) -> str:
    return re.sub(r"\s+", "", str(pattern or "").strip().lower())


def _confidence_rank(label: str) -> int:
    normalized = str(label or "").strip().lower()
    if normalized == "high":
        return 2
    if normalized == "medium":
        return 1
    return 0


def _ensure_semantic_schema(config: dict) -> tuple[dict, list[str]]:
    notes: list[str] = []
    if not isinstance(config.get("profiles"), dict):
        config["profiles"] = {}
        notes.append("Created missing top-level profiles object")

    profiles = config["profiles"]
    if not isinstance(profiles.get("generic"), dict):
        profiles["generic"] = {}
        notes.append("Created missing profiles.generic object")

    generic = profiles["generic"]
    if not isinstance(generic.get("intent_patterns"), dict):
        generic["intent_patterns"] = {}
        notes.append("Created missing profiles.generic.intent_patterns object")

    intent_patterns = generic["intent_patterns"]
    if not isinstance(intent_patterns.get("direct_map_comment_patterns"), list):
        intent_patterns["direct_map_comment_patterns"] = []
        notes.append("Created missing direct_map_comment_patterns list")

    return intent_patterns, notes


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Apply reviewed intent-pattern suggestions into rules/semantic_profiles.json "
            "with dedupe and dry-run support."
        )
    )
    parser.add_argument(
        "--suggestions",
        default="results/ci/intent_pattern_suggestions.json",
        help="Path to suggestion artifact generated by suggest_intent_patterns.py",
    )
    parser.add_argument(
        "--semantic-config",
        default="rules/semantic_profiles.json",
        help="Path to semantic profile config to update",
    )
    parser.add_argument(
        "--min-confidence",
        choices=["high", "medium"],
        default="high",
        help="Minimum confidence level required for applying suggestions",
    )
    parser.add_argument(
        "--min-count",
        type=int,
        default=2,
        help="Minimum occurrence count required for applying suggestions",
    )
    parser.add_argument(
        "--max-ratio-gap",
        type=float,
        default=1.0,
        help=(
            "Optional source-backed ratio gate. Suggestions with ratio below "
            "(1.0 - max_ratio_gap) are excluded. Keep default for no additional filtering."
        ),
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write accepted patterns into semantic config. Without this flag, runs as dry-run.",
    )
    parser.add_argument(
        "--report-out",
        default="results/ci/intent_pattern_apply_report.json",
        help="Path to write apply/dry-run report",
    )
    args = parser.parse_args()

    suggestions_path = Path(args.suggestions)
    semantic_config_path = Path(args.semantic_config)
    report_out_path = Path(args.report_out)

    suggestions_payload = _load_json(suggestions_path)
    semantic_config = _load_json(semantic_config_path)

    suggestions = suggestions_payload.get("suggestions")
    if not isinstance(suggestions, list):
        raise ValueError("Suggestion payload must include a list at key 'suggestions'")

    intent_patterns, schema_notes = _ensure_semantic_schema(semantic_config)
    existing_patterns = intent_patterns.get("direct_map_comment_patterns", [])
    existing_patterns = [str(item).strip() for item in existing_patterns if str(item).strip()]
    existing_keys = {_normalize_pattern_key(item) for item in existing_patterns}

    min_conf_rank = _confidence_rank(args.min_confidence)
    min_ratio = max(0.0, 1.0 - float(args.max_ratio_gap))

    accepted: list[dict] = []
    skipped: list[dict] = []

    for row in suggestions:
        if not isinstance(row, dict):
            continue

        condition = str(row.get("condition") or "").strip()
        proposed_regex = str(row.get("proposed_regex") or "").strip()
        confidence = str(row.get("confidence") or "").strip().lower()
        count = int(row.get("count") or 0)
        source_ratio = float(row.get("source_backed_ratio") or 0.0)

        reason = None
        if not proposed_regex:
            reason = "missing_proposed_regex"
        elif _confidence_rank(confidence) < min_conf_rank:
            reason = "below_min_confidence"
        elif count < int(args.min_count):
            reason = "below_min_count"
        elif source_ratio < min_ratio:
            reason = "below_source_ratio_gate"

        normalized_key = _normalize_pattern_key(proposed_regex)
        if reason is None and normalized_key in existing_keys:
            reason = "already_exists"

        if reason is not None:
            skipped.append(
                {
                    "condition": condition,
                    "proposed_regex": proposed_regex,
                    "confidence": confidence,
                    "count": count,
                    "source_backed_ratio": source_ratio,
                    "reason": reason,
                }
            )
            continue

        accepted.append(
            {
                "condition": condition,
                "proposed_regex": proposed_regex,
                "confidence": confidence,
                "count": count,
                "source_backed_ratio": source_ratio,
            }
        )
        existing_keys.add(normalized_key)

    accepted_patterns = [item["proposed_regex"] for item in accepted]
    updated_patterns = [*existing_patterns, *accepted_patterns]

    applied = False
    if args.apply and accepted_patterns:
        intent_patterns["direct_map_comment_patterns"] = updated_patterns
        semantic_config_path.write_text(json.dumps(semantic_config, indent=2) + "\n", encoding="utf-8")
        applied = True

    report_payload = {
        "suggestions_path": suggestions_path.as_posix(),
        "semantic_config_path": semantic_config_path.as_posix(),
        "mode": "apply" if args.apply else "dry_run",
        "filters": {
            "min_confidence": args.min_confidence,
            "min_count": int(args.min_count),
            "min_source_backed_ratio": min_ratio,
        },
        "schema_notes": schema_notes,
        "existing_pattern_count": len(existing_patterns),
        "accepted_count": len(accepted),
        "skipped_count": len(skipped),
        "final_pattern_count": len(updated_patterns),
        "applied": applied,
        "accepted": accepted,
        "skipped": skipped,
    }

    report_out_path.parent.mkdir(parents=True, exist_ok=True)
    report_out_path.write_text(json.dumps(report_payload, indent=2) + "\n", encoding="utf-8")

    print(f"Mode: {'apply' if args.apply else 'dry-run'}")
    print(f"Existing patterns: {len(existing_patterns)}")
    print(f"Accepted candidates: {len(accepted)}")
    print(f"Skipped candidates: {len(skipped)}")
    print(f"Final pattern count: {len(updated_patterns)}")
    if args.apply:
        print(f"Semantic config updated: {semantic_config_path.as_posix()}")
    else:
        print("Semantic config unchanged (dry-run)")
    print(f"Apply report: {report_out_path.as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
